adb: client: don't build commandline for windows
FAILED: out/soong/.intermediates/system/core/adb/adb/windows_x86/obj/system/core/adb/client/commandline.o
PWD=/proc/self/cwd prebuilts/clang/host/linux-x86/clang-r353983c/bin/clang++ -c -Isystem/core/adb  -DUSE_MINGW -DWIN32_LEAN_AND_MEAN -Wno-unused-parameter -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -D__USE_MINGW_ANSI_STDIO=1 -D_WIN32_WINNT=0x0601 -DWINVER=0x0601 -D_FILE_OFFSET_BITS=64 --sysroot prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8/x86_64-w64-mingw32 -m32 -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasing -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -faddrsig -Wimplicit-fallthrough -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-zero-as-null-pointer-constant -Wno-sign-compare -Wno-defaulted-function-deleted -Wno-inconsistent-missing-override   -Ibuild/soong/cc/libbuildversion/include -Isystem/core/base/include -Isystem/core/libcrypto_utils/include -Iexternal/boringssl/src/include -Isystem/core/diagnose_usb/include -Iexternal/mdnsresponder/mDNSShared -Iexternal/libusb/include -Isystem/core/libutils/include -Isystem/core/liblog/include -Isystem/core/libsystem/include -Isystem/core/libcutils/include -Isystem/core/libprocessgroup/include -Iexternal/libcxx/include -Iexternal/libcxxabi/include -Idevelopment/host/windows/usb/api -Isystem/core/include -Isystem/media/audio/include -Ihardware/libhardware/include -Ihardware/libhardware_legacy/include -Ihardware/ril/include -Iframeworks/native/include -Iframeworks/native/opengl/include -Iframeworks/av/include -isystem prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8/x86_64-w64-mingw32/include -Ilibnativehelper/include_jni -Wall -Wextra -Werror -Wexit-time-destructors -Wno-unused-parameter -Wno-missing-field-initializers -Wthread-safety -Wvla -DADB_HOST=1 -DALLOW_ADBD_ROOT=0 -DUNICODE=1 -D_UNICODE=1 -D_GNU_SOURCE -D_POSIX_SOURCE -Wno-thread-safety -target i686-windows-gnu -Bprebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8/x86_64-w64-mingw32/bin -DANDROID_STRICT -D_USING_LIBCXX -std=gnu++2a -Wsign-promo -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-thread-safety-negative -Wno-gnu-include-next    -nostdinc++ -fsjlj-exceptions -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_HAS_THREAD_API_WIN32 -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-tautological-unsigned-enum-zero-compare -Wno-tautological-unsigned-zero-compare -Wno-c++98-compat-extra-semi -Wno-return-std-move-in-c++11 -MD -MF out/soong/.intermediates/system/core/adb/adb/windows_x86/obj/system/core/adb/client/commandline.o.d -o out/soong/.intermediates/system/core/adb/adb/windows_x86/obj/system/core/adb/client/commandline.o system/core/adb/client/commandline.cpp
system/core/adb/client/commandline.cpp:914:9: error: comparison of integers of different signs: 'SOCKET' (aka 'unsigned int') and 'int' [-Werror,-Wsign-compare]
        FD_SET(device_fd, &fds);
        ^~~~~~~~~~~~~~~~~~~~~~~
prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8/x86_64-w64-mingw32/include/psdk_inc/_fd_types.h:77:40: note: expanded from macro 'FD_SET'
                if (((fd_set *)(set))->fd_array[__i] == (fd)) {         \
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~
1 error generated.

Seems useless enough and I don't wanna fix this rn

Change-Id: I57b53c4f3ca16fc3945267a456f188a58fe867dc
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>